name: Deploy production Green Therapy
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy-production-netlify.yml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Netlify
        run: >-
          npx -y @netlify/mcp@latest
          --site-id 5a7aed51-996b-4be1-aea1-906bc30bb37b
          --proxy-path "https://netlify-mcp.netlify.app/proxy/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..SLvoSmPU2h9A0qpW.D_bemnR2d4VWgtqylLi9esayaNK093ogadz6I-MxcyYF00_Mp-tkGchytUx6UZq-9ILfdNOE1CIdlvJHAjKU9Jc3Sq7m6uetMMAmF3nPpERAm1VRYbknDj0VNYkV0S0Il4ailVddFyDPMX4cHV5DNhpF763-suGxzyS0Mi99V_U0GvOyx0gcA6PBiqZc-4jo9PsJ8rF3IYyaExb7F3REnMDAhiDuBTa_mUTiXN30ST5bFlihE1blYg4XceGuo2l2FGKsD8GYr74hFVnpnZAIpusGc_1IVBB_0w8LMLUstYQXHft93OcFuV7H5i1T51LXnfnI08o8kxrHkYI8J9PB1Ffw1zJy3zCKO9SIxfRj-YhjTx7KYW3NB4P1AGVcUNVTBE411yT-.nkI6Jjz7sDP2RfuIcy0jtw"
